# Generated by Django 5.2.10 on 2026-02-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_car",
                    models.CharField(max_length=100, verbose_name="Название машины"),
                ),
                (
                    "horses",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Мощность в лошадиных силах",
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="В наличии"),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
